In [ ]:
"""
Напишіть код, який здійснює процес перетворення матриці,
наведений у прикладі з презентації.
"""

In [1]:
import numpy as np

In [30]:
matrix = np.array([[4, 2, 0],
                   [1, 3, 2],
                   [-1, 3, 10]])

In [31]:
# Змінюємо місцями перший і другий рядки
matrix[[0, 1]] = matrix[[1, 0]]

In [32]:
print(matrix)

[[ 1  3  2]
 [ 4  2  0]
 [-1  3 10]]


In [33]:
# Додаємо перший рядок, помножений на -4, до другого рядка
matrix[1] += -4 * matrix[0]

In [34]:
# Додаємо перший рядок до третього рядка
matrix[2] += matrix[0]

In [35]:
print(matrix)

[[  1   3   2]
 [  0 -10  -8]
 [  0   6  12]]


In [36]:
# Ділимо другий рядок на -2
matrix[1] = matrix[1].astype(float)/-2

In [37]:
# Ділимо третій рядок на 6
matrix[2] = matrix[2].astype(float)/6

In [38]:
print(matrix)

[[1 3 2]
 [0 5 4]
 [0 1 2]]


In [39]:
# Змінюємо місцями 2-й і 3-й рядки
matrix[[1, 2]] = matrix[[2, 1]]

In [40]:
print(matrix)

[[1 3 2]
 [0 1 2]
 [0 5 4]]


In [41]:
# Додаємо до 3-го рядка 2-й, помножений на -5
matrix[2] += matrix[1] * (-5)

In [42]:
print(matrix)

[[ 1  3  2]
 [ 0  1  2]
 [ 0  0 -6]]
